build:
  image: ruby:2.3
  commands:
    - bundle install --path=bundler
    - rspec spec/
cache:
  mount:
    - bundler
compose:
  mongodb:
    image: mongo:3.2
publish:
  docker:
    username: $$DOCKER_HUB_USER
    password: $$DOCKER_HUB_PWD
    email: $$DOCKER_HUB_EMAIL
    repo: kontena/todo-example
    tag: latest
    file: Dockerfile
notify:
  webhook:
    urls:
      - https://aws-master-1.kontena.io/v1/services/upcloud-drone/todo-app/deploy
    header:
      Authorization: Bearer $$KONTENA_TOKEN
    content_type: application/json
    template: >
      {}
